---
--- Generated by Luanalysis
--- Created by selen.
--- DateTime: 8/11/2023 9:35 PM
---
Test_String = "ABC"
Test_Boolean = true
Test_Int = 5
Test_World = "world"



return {
    Test_String = Test_String,
    Test_Boolean = Test_Boolean,
    Test_Int = Test_Int,
    Test_World = Test_World
}